server:
#  servlet:
#    context-path: /demo
  port: 8086

dubbo:
  application: # ApplicationConfig Bean
    id: dubbo-consumer-demo
    name: dubbo-consumer-demo
  registry:                 #注册中心配置，用于配置连接注册中心相关信息。
    address: zookeeper://127.0.0.1:2181
  protocol:
    id: dubbo
    name: dubbo
    port: -1


