server:
  port: 8081 #项目端口

spring:
  application:
    name: dubbo-server-provider #应用配置，用于配置当前应用信息，
  dubbo:                        #注册中心配置，用于配置连接注册中心相关信息。
    server: true
    registry: zookeeper://127.0.0.1:2181
    protocol:                   #协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受（订阅）
      name: dubbo
      port: 29081
