server:
  port: 8081 #项目端口

dubbo:
  application:
    id: dubbo-provider-demo
    name: dubbo-provider-demo
  scan:
    base-packages: com.example.demo.service   # Base packages to scan Dubbo Component: @com.alibaba.dubbo.config.annotation.Service
  protocol: # Dubbo Protocol
    name: dubbo
    port: -1
  registry: # Dubbo Registry
    address: zookeeper://127.0.0.1:2181  #直连配为 N/A
